// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animalai/communicator_objects/arena_parameters_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from animalai/communicator_objects/arena_parameters_proto.proto</summary>
  public static partial class ArenaParametersProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for animalai/communicator_objects/arena_parameters_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArenaParametersProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjphbmltYWxhaS9jb21tdW5pY2F0b3Jfb2JqZWN0cy9hcmVuYV9wYXJhbWV0",
            "ZXJzX3Byb3RvLnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cyLPAwoUQXJl",
            "bmFQYXJhbWV0ZXJzUHJvdG8SCQoBdBgBIAEoBRJGCgVpdGVtcxgCIAMoCzI3",
            "LmNvbW11bmljYXRvcl9vYmplY3RzLkFyZW5hUGFyYW1ldGVyc1Byb3RvLkl0",
            "ZW1zVG9TcGF3bhIRCglibGFja291dHMYAyADKAUa0AIKDEl0ZW1zVG9TcGF3",
            "bhIMCgRuYW1lGAEgASgJElIKCXBvc2l0aW9ucxgDIAMoCzI/LmNvbW11bmlj",
            "YXRvcl9vYmplY3RzLkFyZW5hUGFyYW1ldGVyc1Byb3RvLkl0ZW1zVG9TcGF3",
            "bi5WZWN0b3IzEhEKCXJvdGF0aW9ucxgEIAMoAhJOCgVzaXplcxgFIAMoCzI/",
            "LmNvbW11bmljYXRvcl9vYmplY3RzLkFyZW5hUGFyYW1ldGVyc1Byb3RvLkl0",
            "ZW1zVG9TcGF3bi5WZWN0b3IzEk8KBmNvbG9ycxgGIAMoCzI/LmNvbW11bmlj",
            "YXRvcl9vYmplY3RzLkFyZW5hUGFyYW1ldGVyc1Byb3RvLkl0ZW1zVG9TcGF3",
            "bi5WZWN0b3IzGioKB1ZlY3RvcjMSCQoBeBgBIAEoAhIJCgF5GAIgASgCEgkK",
            "AXoYAyABKAJCH6oCHE1MQWdlbnRzLkNvbW11bmljYXRvck9iamVjdHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.ArenaParametersProto), global::MLAgents.CommunicatorObjects.ArenaParametersProto.Parser, new[]{ "T", "Items", "Blackouts" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn), global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Parser, new[]{ "Name", "Positions", "Rotations", "Sizes", "Colors" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3), global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3.Parser, new[]{ "X", "Y", "Z" }, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ArenaParametersProto : pb::IMessage<ArenaParametersProto> {
    private static readonly pb::MessageParser<ArenaParametersProto> _parser = new pb::MessageParser<ArenaParametersProto>(() => new ArenaParametersProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ArenaParametersProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.ArenaParametersProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArenaParametersProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArenaParametersProto(ArenaParametersProto other) : this() {
      t_ = other.t_;
      items_ = other.items_.Clone();
      blackouts_ = other.blackouts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ArenaParametersProto Clone() {
      return new ArenaParametersProto(this);
    }

    /// <summary>Field number for the "t" field.</summary>
    public const int TFieldNumber = 1;
    private int t_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int T {
      get { return t_; }
      set {
        t_ = value;
      }
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn> _repeated_items_codec
        = pb::FieldCodec.ForMessage(18, global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Parser);
    private readonly pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn> items_ = new pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "blackouts" field.</summary>
    public const int BlackoutsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_blackouts_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> blackouts_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> Blackouts {
      get { return blackouts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ArenaParametersProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ArenaParametersProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (T != other.T) return false;
      if(!items_.Equals(other.items_)) return false;
      if(!blackouts_.Equals(other.blackouts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (T != 0) hash ^= T.GetHashCode();
      hash ^= items_.GetHashCode();
      hash ^= blackouts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (T != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(T);
      }
      items_.WriteTo(output, _repeated_items_codec);
      blackouts_.WriteTo(output, _repeated_blackouts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (T != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(T);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      size += blackouts_.CalculateSize(_repeated_blackouts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ArenaParametersProto other) {
      if (other == null) {
        return;
      }
      if (other.T != 0) {
        T = other.T;
      }
      items_.Add(other.items_);
      blackouts_.Add(other.blackouts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            T = input.ReadInt32();
            break;
          }
          case 18: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 26:
          case 24: {
            blackouts_.AddEntriesFrom(input, _repeated_blackouts_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ArenaParametersProto message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ItemsToSpawn : pb::IMessage<ItemsToSpawn> {
        private static readonly pb::MessageParser<ItemsToSpawn> _parser = new pb::MessageParser<ItemsToSpawn>(() => new ItemsToSpawn());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ItemsToSpawn> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::MLAgents.CommunicatorObjects.ArenaParametersProto.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ItemsToSpawn() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ItemsToSpawn(ItemsToSpawn other) : this() {
          name_ = other.name_;
          positions_ = other.positions_.Clone();
          rotations_ = other.rotations_.Clone();
          sizes_ = other.sizes_.Clone();
          colors_ = other.colors_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ItemsToSpawn Clone() {
          return new ItemsToSpawn(this);
        }

        /// <summary>Field number for the "name" field.</summary>
        public const int NameFieldNumber = 1;
        private string name_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "positions" field.</summary>
        public const int PositionsFieldNumber = 3;
        private static readonly pb::FieldCodec<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> _repeated_positions_codec
            = pb::FieldCodec.ForMessage(26, global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3.Parser);
        private readonly pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> positions_ = new pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> Positions {
          get { return positions_; }
        }

        /// <summary>Field number for the "rotations" field.</summary>
        public const int RotationsFieldNumber = 4;
        private static readonly pb::FieldCodec<float> _repeated_rotations_codec
            = pb::FieldCodec.ForFloat(34);
        private readonly pbc::RepeatedField<float> rotations_ = new pbc::RepeatedField<float>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<float> Rotations {
          get { return rotations_; }
        }

        /// <summary>Field number for the "sizes" field.</summary>
        public const int SizesFieldNumber = 5;
        private static readonly pb::FieldCodec<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> _repeated_sizes_codec
            = pb::FieldCodec.ForMessage(42, global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3.Parser);
        private readonly pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> sizes_ = new pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> Sizes {
          get { return sizes_; }
        }

        /// <summary>Field number for the "colors" field.</summary>
        public const int ColorsFieldNumber = 6;
        private static readonly pb::FieldCodec<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> _repeated_colors_codec
            = pb::FieldCodec.ForMessage(50, global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3.Parser);
        private readonly pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> colors_ = new pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Types.Vector3> Colors {
          get { return colors_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ItemsToSpawn);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ItemsToSpawn other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Name != other.Name) return false;
          if(!positions_.Equals(other.positions_)) return false;
          if(!rotations_.Equals(other.rotations_)) return false;
          if(!sizes_.Equals(other.sizes_)) return false;
          if(!colors_.Equals(other.colors_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          hash ^= positions_.GetHashCode();
          hash ^= rotations_.GetHashCode();
          hash ^= sizes_.GetHashCode();
          hash ^= colors_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Name.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Name);
          }
          positions_.WriteTo(output, _repeated_positions_codec);
          rotations_.WriteTo(output, _repeated_rotations_codec);
          sizes_.WriteTo(output, _repeated_sizes_codec);
          colors_.WriteTo(output, _repeated_colors_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          size += positions_.CalculateSize(_repeated_positions_codec);
          size += rotations_.CalculateSize(_repeated_rotations_codec);
          size += sizes_.CalculateSize(_repeated_sizes_codec);
          size += colors_.CalculateSize(_repeated_colors_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ItemsToSpawn other) {
          if (other == null) {
            return;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          positions_.Add(other.positions_);
          rotations_.Add(other.rotations_);
          sizes_.Add(other.sizes_);
          colors_.Add(other.colors_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Name = input.ReadString();
                break;
              }
              case 26: {
                positions_.AddEntriesFrom(input, _repeated_positions_codec);
                break;
              }
              case 34:
              case 37: {
                rotations_.AddEntriesFrom(input, _repeated_rotations_codec);
                break;
              }
              case 42: {
                sizes_.AddEntriesFrom(input, _repeated_sizes_codec);
                break;
              }
              case 50: {
                colors_.AddEntriesFrom(input, _repeated_colors_codec);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the ItemsToSpawn message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public sealed partial class Vector3 : pb::IMessage<Vector3> {
            private static readonly pb::MessageParser<Vector3> _parser = new pb::MessageParser<Vector3>(() => new Vector3());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<Vector3> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::MLAgents.CommunicatorObjects.ArenaParametersProto.Types.ItemsToSpawn.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Vector3() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Vector3(Vector3 other) : this() {
              x_ = other.x_;
              y_ = other.y_;
              z_ = other.z_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public Vector3 Clone() {
              return new Vector3(this);
            }

            /// <summary>Field number for the "x" field.</summary>
            public const int XFieldNumber = 1;
            private float x_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public float X {
              get { return x_; }
              set {
                x_ = value;
              }
            }

            /// <summary>Field number for the "y" field.</summary>
            public const int YFieldNumber = 2;
            private float y_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public float Y {
              get { return y_; }
              set {
                y_ = value;
              }
            }

            /// <summary>Field number for the "z" field.</summary>
            public const int ZFieldNumber = 3;
            private float z_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public float Z {
              get { return z_; }
              set {
                z_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as Vector3);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(Vector3 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
              if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
              if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (X != 0F) {
                output.WriteRawTag(13);
                output.WriteFloat(X);
              }
              if (Y != 0F) {
                output.WriteRawTag(21);
                output.WriteFloat(Y);
              }
              if (Z != 0F) {
                output.WriteRawTag(29);
                output.WriteFloat(Z);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (X != 0F) {
                size += 1 + 4;
              }
              if (Y != 0F) {
                size += 1 + 4;
              }
              if (Z != 0F) {
                size += 1 + 4;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(Vector3 other) {
              if (other == null) {
                return;
              }
              if (other.X != 0F) {
                X = other.X;
              }
              if (other.Y != 0F) {
                Y = other.Y;
              }
              if (other.Z != 0F) {
                Z = other.Z;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 13: {
                    X = input.ReadFloat();
                    break;
                  }
                  case 21: {
                    Y = input.ReadFloat();
                    break;
                  }
                  case 29: {
                    Z = input.ReadFloat();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
