// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animalai/communicator_objects/space_type_proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from animalai/communicator_objects/space_type_proto.proto</summary>
  public static partial class SpaceTypeProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for animalai/communicator_objects/space_type_proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpaceTypeProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRhbmltYWxhaS9jb21tdW5pY2F0b3Jfb2JqZWN0cy9zcGFjZV90eXBlX3By",
            "b3RvLnByb3RvEhRjb21tdW5pY2F0b3Jfb2JqZWN0cxo0YW5pbWFsYWkvY29t",
            "bXVuaWNhdG9yX29iamVjdHMvcmVzb2x1dGlvbl9wcm90by5wcm90byouCg5T",
            "cGFjZVR5cGVQcm90bxIMCghkaXNjcmV0ZRAAEg4KCmNvbnRpbnVvdXMQAUIf",
            "qgIcTUxBZ2VudHMuQ29tbXVuaWNhdG9yT2JqZWN0c2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.ResolutionProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MLAgents.CommunicatorObjects.SpaceTypeProto), }, null));
    }
    #endregion

  }
  #region Enums
  public enum SpaceTypeProto {
    [pbr::OriginalName("discrete")] Discrete = 0,
    [pbr::OriginalName("continuous")] Continuous = 1,
  }

  #endregion

}

#endregion Designer generated code
