// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animalai/communicator_objects/unity_input.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from animalai/communicator_objects/unity_input.proto</summary>
  public static partial class UnityInputReflection {

    #region Descriptor
    /// <summary>File descriptor for animalai/communicator_objects/unity_input.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityInputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci9hbmltYWxhaS9jb21tdW5pY2F0b3Jfb2JqZWN0cy91bml0eV9pbnB1dC5w",
            "cm90bxIUY29tbXVuaWNhdG9yX29iamVjdHMaMmFuaW1hbGFpL2NvbW11bmlj",
            "YXRvcl9vYmplY3RzL3VuaXR5X3JsX2lucHV0LnByb3RvGkFhbmltYWxhaS9j",
            "b21tdW5pY2F0b3Jfb2JqZWN0cy91bml0eV9ybF9pbml0aWFsaXphdGlvbl9p",
            "bnB1dC5wcm90bxo4YW5pbWFsYWkvY29tbXVuaWNhdG9yX29iamVjdHMvdW5p",
            "dHlfcmxfcmVzZXRfaW5wdXQucHJvdG8i1gEKClVuaXR5SW5wdXQSNAoIcmxf",
            "aW5wdXQYASABKAsyIi5jb21tdW5pY2F0b3Jfb2JqZWN0cy5Vbml0eVJMSW5w",
            "dXQSUQoXcmxfaW5pdGlhbGl6YXRpb25faW5wdXQYAiABKAsyMC5jb21tdW5p",
            "Y2F0b3Jfb2JqZWN0cy5Vbml0eVJMSW5pdGlhbGl6YXRpb25JbnB1dBI/Cg5y",
            "bF9yZXNldF9pbnB1dBgDIAEoCzInLmNvbW11bmljYXRvcl9vYmplY3RzLlVu",
            "aXR5UkxSZXNldElucHV0Qh+qAhxNTEFnZW50cy5Db21tdW5pY2F0b3JPYmpl",
            "Y3RzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.UnityRlInputReflection.Descriptor, global::MLAgents.CommunicatorObjects.UnityRlInitializationInputReflection.Descriptor, global::MLAgents.CommunicatorObjects.UnityRlResetInputReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.UnityInput), global::MLAgents.CommunicatorObjects.UnityInput.Parser, new[]{ "RlInput", "RlInitializationInput", "RlResetInput" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityInput : pb::IMessage<UnityInput> {
    private static readonly pb::MessageParser<UnityInput> _parser = new pb::MessageParser<UnityInput>(() => new UnityInput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityInput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.UnityInputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInput(UnityInput other) : this() {
      rlInput_ = other.rlInput_ != null ? other.rlInput_.Clone() : null;
      rlInitializationInput_ = other.rlInitializationInput_ != null ? other.rlInitializationInput_.Clone() : null;
      rlResetInput_ = other.rlResetInput_ != null ? other.rlResetInput_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityInput Clone() {
      return new UnityInput(this);
    }

    /// <summary>Field number for the "rl_input" field.</summary>
    public const int RlInputFieldNumber = 1;
    private global::MLAgents.CommunicatorObjects.UnityRLInput rlInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.UnityRLInput RlInput {
      get { return rlInput_; }
      set {
        rlInput_ = value;
      }
    }

    /// <summary>Field number for the "rl_initialization_input" field.</summary>
    public const int RlInitializationInputFieldNumber = 2;
    private global::MLAgents.CommunicatorObjects.UnityRLInitializationInput rlInitializationInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.UnityRLInitializationInput RlInitializationInput {
      get { return rlInitializationInput_; }
      set {
        rlInitializationInput_ = value;
      }
    }

    /// <summary>Field number for the "rl_reset_input" field.</summary>
    public const int RlResetInputFieldNumber = 3;
    private global::MLAgents.CommunicatorObjects.UnityRLResetInput rlResetInput_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::MLAgents.CommunicatorObjects.UnityRLResetInput RlResetInput {
      get { return rlResetInput_; }
      set {
        rlResetInput_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityInput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityInput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RlInput, other.RlInput)) return false;
      if (!object.Equals(RlInitializationInput, other.RlInitializationInput)) return false;
      if (!object.Equals(RlResetInput, other.RlResetInput)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (rlInput_ != null) hash ^= RlInput.GetHashCode();
      if (rlInitializationInput_ != null) hash ^= RlInitializationInput.GetHashCode();
      if (rlResetInput_ != null) hash ^= RlResetInput.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (rlInput_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RlInput);
      }
      if (rlInitializationInput_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RlInitializationInput);
      }
      if (rlResetInput_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(RlResetInput);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (rlInput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RlInput);
      }
      if (rlInitializationInput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RlInitializationInput);
      }
      if (rlResetInput_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RlResetInput);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityInput other) {
      if (other == null) {
        return;
      }
      if (other.rlInput_ != null) {
        if (rlInput_ == null) {
          RlInput = new global::MLAgents.CommunicatorObjects.UnityRLInput();
        }
        RlInput.MergeFrom(other.RlInput);
      }
      if (other.rlInitializationInput_ != null) {
        if (rlInitializationInput_ == null) {
          RlInitializationInput = new global::MLAgents.CommunicatorObjects.UnityRLInitializationInput();
        }
        RlInitializationInput.MergeFrom(other.RlInitializationInput);
      }
      if (other.rlResetInput_ != null) {
        if (rlResetInput_ == null) {
          RlResetInput = new global::MLAgents.CommunicatorObjects.UnityRLResetInput();
        }
        RlResetInput.MergeFrom(other.RlResetInput);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (rlInput_ == null) {
              RlInput = new global::MLAgents.CommunicatorObjects.UnityRLInput();
            }
            input.ReadMessage(RlInput);
            break;
          }
          case 18: {
            if (rlInitializationInput_ == null) {
              RlInitializationInput = new global::MLAgents.CommunicatorObjects.UnityRLInitializationInput();
            }
            input.ReadMessage(RlInitializationInput);
            break;
          }
          case 26: {
            if (rlResetInput_ == null) {
              RlResetInput = new global::MLAgents.CommunicatorObjects.UnityRLResetInput();
            }
            input.ReadMessage(RlResetInput);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
