// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animalai/communicator_objects/unity_to_external.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from animalai/communicator_objects/unity_to_external.proto</summary>
  public static partial class UnityToExternalReflection {

    #region Descriptor
    /// <summary>File descriptor for animalai/communicator_objects/unity_to_external.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityToExternalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjVhbmltYWxhaS9jb21tdW5pY2F0b3Jfb2JqZWN0cy91bml0eV90b19leHRl",
            "cm5hbC5wcm90bxIUY29tbXVuaWNhdG9yX29iamVjdHMaMWFuaW1hbGFpL2Nv",
            "bW11bmljYXRvcl9vYmplY3RzL3VuaXR5X21lc3NhZ2UucHJvdG8yZwoPVW5p",
            "dHlUb0V4dGVybmFsElQKCEV4Y2hhbmdlEiIuY29tbXVuaWNhdG9yX29iamVj",
            "dHMuVW5pdHlNZXNzYWdlGiIuY29tbXVuaWNhdG9yX29iamVjdHMuVW5pdHlN",
            "ZXNzYWdlIgBCH6oCHE1MQWdlbnRzLkNvbW11bmljYXRvck9iamVjdHNiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MLAgents.CommunicatorObjects.UnityMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
