// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: animalai/communicator_objects/unity_rl_reset_output.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MLAgents.CommunicatorObjects {

  /// <summary>Holder for reflection information generated from animalai/communicator_objects/unity_rl_reset_output.proto</summary>
  public static partial class UnityRlResetOutputReflection {

    #region Descriptor
    /// <summary>File descriptor for animalai/communicator_objects/unity_rl_reset_output.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnityRlResetOutputReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjlhbmltYWxhaS9jb21tdW5pY2F0b3Jfb2JqZWN0cy91bml0eV9ybF9yZXNl",
            "dF9vdXRwdXQucHJvdG8SFGNvbW11bmljYXRvcl9vYmplY3RzIjEKElVuaXR5",
            "UkxSZXNldE91dHB1dBIbChNhcmVuYXNfaW5zdGFuY2lhdGVkGAEgAygIQh+q",
            "AhxNTEFnZW50cy5Db21tdW5pY2F0b3JPYmplY3RzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MLAgents.CommunicatorObjects.UnityRLResetOutput), global::MLAgents.CommunicatorObjects.UnityRLResetOutput.Parser, new[]{ "ArenasInstanciated" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UnityRLResetOutput : pb::IMessage<UnityRLResetOutput> {
    private static readonly pb::MessageParser<UnityRLResetOutput> _parser = new pb::MessageParser<UnityRLResetOutput>(() => new UnityRLResetOutput());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UnityRLResetOutput> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MLAgents.CommunicatorObjects.UnityRlResetOutputReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLResetOutput() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLResetOutput(UnityRLResetOutput other) : this() {
      arenasInstanciated_ = other.arenasInstanciated_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UnityRLResetOutput Clone() {
      return new UnityRLResetOutput(this);
    }

    /// <summary>Field number for the "arenas_instanciated" field.</summary>
    public const int ArenasInstanciatedFieldNumber = 1;
    private static readonly pb::FieldCodec<bool> _repeated_arenasInstanciated_codec
        = pb::FieldCodec.ForBool(10);
    private readonly pbc::RepeatedField<bool> arenasInstanciated_ = new pbc::RepeatedField<bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<bool> ArenasInstanciated {
      get { return arenasInstanciated_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UnityRLResetOutput);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UnityRLResetOutput other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!arenasInstanciated_.Equals(other.arenasInstanciated_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= arenasInstanciated_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      arenasInstanciated_.WriteTo(output, _repeated_arenasInstanciated_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += arenasInstanciated_.CalculateSize(_repeated_arenasInstanciated_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UnityRLResetOutput other) {
      if (other == null) {
        return;
      }
      arenasInstanciated_.Add(other.arenasInstanciated_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            arenasInstanciated_.AddEntriesFrom(input, _repeated_arenasInstanciated_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
